// Professional Portfolio — CV-derived, pre-populated content.
//
// Source of truth: M.Suleman_CV.md (repo root), per docs/portfolio-spec.md §2.3/§10.2. This module
// is the ONLY place this content lives — it is never entered through the admin Portfolio form
// (apps/admin/app/portfolio/page.tsx), which manages real work-sample media only (spec §11).
//
// Every entry below carries a `sourceTrace` string pointing at the exact CV section(s) it came
// from and, where relevant, the docs/portfolio-spec.md §2.4 row that documents how a conflict or
// gap between the CV's two source sections was resolved. Nothing here is invented; wording that
// reads as a verbatim CV bullet (including the source's own minor phrasing/typos, e.g. "through
// inspections", "far audit purposes") is left as written, per the spec's "do not silently correct
// source wording" instruction — this is preserved source content, not new copywriting.
//
// Do not edit this file to "fix" wording without checking it against M.Suleman_CV.md first — see
// docs/portfolio-spec.md §2.4 for the full conflict/traceability log.

export interface ExperienceEntry {
  employer: string;
  title: string;
  dates: string;
  bullets: string[];
  sourceTrace: string;
}

export interface EducationEntry {
  credential: string;
  institution: string;
  detail: string;
  sourceTrace?: string;
}

export const portfolioProfileContent = {
  identity: {
    name: 'M. Suleman Yaseen',
    // Spec-drafted descriptor (docs/portfolio-spec.md §5.1), grounded in the CV 1 section's
    // "Digitizer (Embroidery Designer)"/"Quality Checker" titles and the CV 2 section's own
    // self-description, "textile and sourcing professional".
    descriptor: 'Embroidery Digitizer & Quality Control Specialist — Textile Sourcing Professional',
  },

  // §2.4 row 1 — business-owner-directed merge, embroidery-primary / textile-secondary, built
  // only from phrases already present in both CV sections' own Profile paragraphs.
  profile: {
    text: "M. Suleman Yaseen is an embroidery digitizing and quality-control professional with a diverse background in embroidery logo design, specializing in Wilcom Embroidery Software and Pulse Tajima Embroidery Software to produce high-quality, intricate embroidery designs that meet and exceed client expectations. Alongside this embroidery-focused expertise, he brings additional professional experience in textile and fabric sourcing, vendor and mill coordination, and supply chain operations in the apparel industry — skilled in purchase order management, sample development, inventory control, ERP systems, and documentation management, with a proven ability to coordinate across sourcing, merchandising, warehouse, and finance teams.",
    sourceTrace: "Sentence 1 merges the CV 1 section's Profile; sentence 2 merges the CV 2 section's Profile. §2.4 row 1.",
  },

  // Synthesized capability summary — deliberately not a bullet reproduction (docs/portfolio-spec.md
  // §5.3). Full, per-employer attributed detail lives in `experience` below.
  coreEmbroideryExpertise: {
    summary:
      'Hands-on expertise across the full embroidery digitizing lifecycle — from converting client artwork and logos into production-ready stitch files, to inspecting finished designs against customer specifications before they reach the production floor.',
    highlights: [
      'Logo digitizing',
      'Complex pattern digitizing',
      'Large-scale export production',
      'Embroidery quality inspection',
      'Customer-specification compliance',
    ],
  },

  softwareExpertise: {
    primary: ['Wilcom Embroidery Software', 'Pulse Tajima Embroidery Software'],
    secondary: ['Oracle ERP', 'Microsoft Excel', 'Microsoft Word', 'Microsoft PowerPoint'],
  },

  // §5.5 — the embroidery-related job timeline. Per §2.4 row 9, ZDigitizing and Vogue Vesture each
  // retain their own full, independently documented responsibilities — nothing merged, moved, or
  // suppressed, even where wording overlaps between the two.
  experience: [
    {
      employer: 'Vogue Vesture',
      title: 'Embroidery Digitizer',
      dates: 'March 2019 – February 2022',
      bullets: [
        // CV 1 section's own Vogue Vesture entry (7 bullets).
        'Working on Wilcom Embroidery Software and Pulse Tajima Software.',
        'Optimized and improved design processes to enhance efficiency and output quality.',
        "Coordinated closely with clients to understand their design requirements, ensuring customer satisfaction.",
        'Specialized in converting client logos into high quality embroidery designs for large-scale export using Pulse Tajima Embroidery Software.',
        'Digitized complex embroidery patterns using wilcom embroidery software, enhancing design accuracy and customer satisfaction.',
        'Managed and organized design projects to meet client specifications and deadlines efficiently.',
        'Utilized specialized embroidery software to develop accurate digital designs for large-scale production.',
        // CV 2 section's own Vogue Vesture entry (6 bullets) — documented there independently of
        // ZDigitizing's entry below; retained here per §2.4 row 9, not moved or deduplicated away.
        'Export logo designing on Wilcom embroidery software and Pluse tajima software.',
        'Conducted through inspections of digitized embroidery designs for accuracy and quality.',
        'Verified compliance with customer specifications and production requirements.',
        'Collaborated with the design team to identify and rectify issues in embroidery outputs.',
        'Lead a training session for new team members to ensure adherence to quality standards in embroidery checking.',
        'Maintained updated records of quality checks and production outcomes far audit purposes.',
      ],
      sourceTrace:
        "Title: CV 1 section says 'Digitizer (Embroidery Designer)', CV 2 section says 'Embroidery Digitizer' (used here). Dates: CV 1 section only (CV 2 section gives none). Bullets: union of both sections' own Vogue Vesture entries, per business-owner decision — §2.4 row 9. Several bullets read similarly to ZDigitizing's below; both are shown in full, per-source, not merged or suppressed.",
    },
    {
      employer: 'ZDigitizing',
      title: 'Quality Checker',
      dates: 'April 2021 – Present',
      bullets: [
        'Export logo designing on Wilcom embroidery software and Pulse Tajima software.',
        'Conducted through inspections of digitized embroidery designs for accuracy and quality.',
        'Verified compliance with customer specifications and production requirements.',
        'Collaborated with the design team to identify and rectify issues in embroidery outputs.',
        'Lead a training session for new team members to ensure adherence to quality standards in embroidery checking.',
        'Maintained updated records of quality checks and production outcomes far audit purposes.',
        'Suggested improvements to the digitization process to enhance overall quality and efficiency.',
        'Developed a systematic review process for catching errors before final embroidery production, improving output accuracy by 20%.',
      ],
      sourceTrace: 'CV 1 section only; the CV 2 section does not mention this employer. §2.4 row 6.',
    },
    {
      employer: 'Freelance',
      title: 'Freelance Embroidery Digitizer',
      dates: 'April 2021 – Present',
      bullets: [
        // Verbatim from the CV 1 section, including its own run-on phrasing — not smoothed.
        'Work as a Freelancer Collaborated with international clients to deliver custom embroidery designs, utilizing advanced digitization techniques.',
        'Developed a reputation for precision and creativity in embroidery digitization through freelance work.',
        'Maintained a steady flow of freelance projects, ensuring timely delivery of high-quality embroidery designs.',
        'Employed effective time management skills to handle multiple freelance projects concurrently, maintaining high standards.',
        'Utilized freelance platforms to market digitizing services, expanding client base significantly.',
      ],
      sourceTrace: 'CV 1 section only; the CV 2 section does not mention this. §2.4 row 12.',
    },
  ] satisfies ExperienceEntry[],

  textileSourcingExpertise: {
    employer: 'Us Apparel',
    title: 'Merchandiser, Fabric Sourcing',
    dates: 'Ongoing (source: "Continue")',
    bullets: [
      'Managed fabric sourcing operations and coordinated with mills/vendors for timely procurement.',
      'Prepared and processed Purchase Orders (POs) for fabric and accessories.',
      'Coordinated sample fabric sourcing for new garment development, managed purchase orders and invoices, and ensured timely vendor payments within 7–15 days.',
      'Coordinated the arrangement of fabric hangers and technical detail files to support merchandising and streamline daily operations.',
      'Coordinated Letter of Credit (LC) requests and followed up on payment processing.',
      'Maintained records of invoices, purchase orders, and payment transactions.',
      'Arranged fabric samples for sampling, development, and buyer approvals.',
      'Maintained complete documentation related to fabric transactions, including Transaction Certificates and BCI Units records.',
      'Monitored and recorded daily fabric issuance and fabric arrival status.',
      'Arranging all fabric-related documents such as packing lists, test reports, invoices, and shipment documents.',
      'Added new fabric item codes in ERP systems according to fabric specifications.',
      'Coordinated with mills to obtain updated fabric pricing and quotations.',
      'Arranged counter-matching fabrics according to buyer requirements and quality standards.',
      'Maintained daily stock reports and monitored fabric inventory levels.',
      'Ensured accurate documentation and smooth coordination between sourcing, merchandising, warehouse, and finance departments.',
      'Responsible for coordinating fabric positioning and lifting from mills within allocated timelines to ensure smooth production flow and on-time material availability.',
    ],
    sourceTrace: 'CV 2 section only; the CV 1 section does not mention this employer. §2.4 row 10.',
  },

  auditExpertise: {
    employer: 'Cross Stitch',
    title: 'Internal Audit Officer',
    dates: 'June 2024 – Present',
    bullets: [
      // CV 1 section (5 bullets).
      'Coordinated with audit team to schedule and organize audit timelines and milestones.',
      'Designed internal control policies to improve audit scores.',
      'Communicated effectively with colleagues regarding audit-related matters.',
      "Worked under supervision of auditors to develop working knowledge of company's audit approach, tools and methods.",
      'Evaluated current policies, procedures, controls, and systems for effectiveness.',
      // CV 2 section (16 bullets) — union per §2.4 row 5, elaboration not contradiction.
      'Checked the stock movement the ware house.',
      'Audit Embroidery Machine and monthly usage of threads and garments.',
      'Checked stock movement FG Store to outlets.',
      'Randomly audited outlets.',
      'Monitored and Controlled inventory levels, ensuring accurate tracking and reporting.',
      'Inventory Management.',
      'Scanning barcodes for Audit purpose and taking record of inventory.',
      'Conducted monthly audit warehouses.',
      'Checked daily sales.',
      'Audit Damage Sale of inventory.',
      'Checked labor wages and audited overtime for employees.',
      'Audited expenses such as petty cash and miscellaneous expenses.',
      'Audited allowances given to employees.',
      'Prepared monthly reports. (Friends and Family Report, Employee Usage Access report, Credit Card Report, Exchanges Report Etc.)',
    ],
    sourceTrace: "Dates: CV 1 section only. Bullets: union of both sections' own Cross Stitch entries. §2.4 rows 4, 5.",
  },

  keySkills: [
    'Software Application',
    'Analyzing Data',
    'Audit Procedure',
    'Report preparation',
    'Quality Control',
    'Microsoft Excel, Word, PowerPoint',
    'Oracle ERP',
  ],

  education: {
    published: [
      { credential: 'Bachelor of Business Administration (BBA), Marketing', institution: 'Arid University of Rawalpindi', detail: 'CGPA 3.52' },
      { credential: 'FSc, Intermediate in Engineering', institution: 'Superior Group of Colleges, Lahore', detail: '60%' },
      { credential: 'Matriculation, Science', institution: 'Universal Public High School, Lahore', detail: '80%' },
      {
        credential: 'MBA, Marketing',
        institution: 'Leads University, Lahore',
        detail: 'Completed',
        sourceTrace:
          "Source text (CV 2 section only) reads 'Bachelor of Business Administrations(MBA Marketing Continue) • Leads University • Lahore • Last semester' — internally ambiguous between BBA-continuation and MBA. Published per business-owner decision using the source's own parenthetical degree name ('MBA Marketing') and presented as completed; the literal 'Continue'/'Last semester' source wording is not reused publicly. §2.4 row 13.",
      },
    ] satisfies EducationEntry[],
  },

  additionalExperience: [
    {
      employer: 'Nagina Group of Industries',
      title: 'Internship Student',
      dates: 'Dates not available in source',
      bullets: [
        // Verbatim from the CV 2 section, including its own run-on/typo phrasing — not smoothed.
        'Managed yarn sales operations, fostering client relationships, and driving revenue growth.',
        'Executed dynamic marketing campaigns, enhancing brand visibility and market penetration Maintained records of al activities related to various projects.',
        'Worked well in team environment as well as independently. Shadowed staff and learned advanced work.',
        'Implemented strategies to take advantage of new opportunities.',
        'Identified needs of customers promptly and efficiently.',
        'Utilized documents management system to organize company files, keeping up to date and easily accessible data.',
        'Collaborate closely with team member to achieves project objectives and meet deadlines.',
      ],
      sourceTrace: 'CV 2 section only, no dates given — displayed undated, not invented. §2.4 row 11.',
    },
  ],

  activities: ['Reading books', 'Taekwondo', 'Travel'],
} as const;
