// Professional Portfolio — CV-derived, pre-populated content.
//
// Source of truth: M.Suleman_CV.md (repo root), per docs/portfolio-spec.md §2.3/§10.2. This module
// is the ONLY place this content lives — it is never entered through the admin Portfolio form
// (apps/admin/app/portfolio/page.tsx), which manages real work-sample media only (spec §11).
//
// Every entry below carries a `sourceTrace` string pointing at the exact CV section(s) it came
// from and, where relevant, the docs/portfolio-spec.md §2.4 row that documents how a conflict or
// gap between the CV's two source sections was resolved. Nothing here is invented; wording that
// reads as a verbatim CV bullet (including the source's own minor phrasing/typos, e.g. "through
// inspections", "far audit purposes") is left as written, per the spec's "do not silently correct
// source wording" instruction — this is preserved source content, not new copywriting.
//
// Do not edit this file to "fix" wording without checking it against M.Suleman_CV.md first — see
// docs/portfolio-spec.md §2.4 for the full conflict/traceability log.
//
// Revision 2026-09-18 (business-owner decision, see docs/portfolio-spec.md revision note): the
// public Professional Experience section no longer names individual employers or lists their
// per-employer responsibilities. It now shows a single consolidated "Freelancer" entry instead.
// Vogue Vesture, ZDigitizing, and the Nagina Group additional-experience entry are removed from
// public display; the CV facts themselves remain preserved in docs/portfolio-spec.md §2.4 for
// the record.
//
// Revision 2026-09-28 (business-owner decision): the Textile & Sourcing Expertise (Us Apparel) and
// Internal Audit/Operational Expertise (Cross Stitch) sections are removed from public display for
// the same reason — no employer name or per-employer responsibility list appears anywhere on the
// public Portfolio page. The CV facts remain preserved in docs/portfolio-spec.md §2.4 rows 4, 5, 10.

export interface ExperienceEntry {
  employer: string;
  title: string;
  dates: string;
  bullets: string[];
  sourceTrace: string;
}

export interface EducationEntry {
  credential: string;
  institution: string;
  detail: string;
  sourceTrace?: string;
}

export const portfolioProfileContent = {
  identity: {
    name: 'M. Suleman Yaseen',
    // Spec-drafted descriptor (docs/portfolio-spec.md §5.1), grounded in the CV 1 section's
    // "Digitizer (Embroidery Designer)"/"Quality Checker" titles and the CV 2 section's own
    // self-description, "textile and sourcing professional".
    descriptor: 'Embroidery Digitizer & Quality Control Specialist — Textile Sourcing Professional',
  },

  // §2.4 row 1 — business-owner-directed merge, embroidery-primary / textile-secondary, built
  // only from phrases already present in both CV sections' own Profile paragraphs.
  profile: {
    text: "M. Suleman Yaseen is an embroidery digitizing and quality-control professional with a diverse background in embroidery logo design, specializing in Wilcom Embroidery Software and Pulse Tajima Embroidery Software to produce high-quality, intricate embroidery designs that meet and exceed client expectations. Alongside this embroidery-focused expertise, he brings additional professional experience in textile and fabric sourcing, vendor and mill coordination, and supply chain operations in the apparel industry — skilled in purchase order management, sample development, inventory control, ERP systems, and documentation management, with a proven ability to coordinate across sourcing, merchandising, warehouse, and finance teams.",
    sourceTrace: "Sentence 1 merges the CV 1 section's Profile; sentence 2 merges the CV 2 section's Profile. §2.4 row 1.",
  },

  // Synthesized capability summary — deliberately not a bullet reproduction (docs/portfolio-spec.md
  // §5.3). Full, per-employer attributed detail lives in `experience` below.
  coreEmbroideryExpertise: {
    summary:
      'Hands-on expertise across the full embroidery digitizing lifecycle — from converting client artwork and logos into production-ready stitch files, to inspecting finished designs against customer specifications before they reach the production floor.',
    highlights: [
      'Logo digitizing',
      'Complex pattern digitizing',
      'Large-scale export production',
      'Embroidery quality inspection',
      'Customer-specification compliance',
    ],
  },

  softwareExpertise: {
    primary: ['Wilcom Embroidery Software', 'Pulse Tajima Embroidery Software'],
    secondary: ['Oracle ERP', 'Microsoft Excel', 'Microsoft Word', 'Microsoft PowerPoint'],
  },

  // Revision 2026-09-18 — public Professional Experience is now a single consolidated
  // "Freelancer" entry; individual employer names and their per-employer responsibility lists
  // (previously Vogue Vesture and ZDigitizing, §2.4 rows 6-9) are no longer published here.
  experience: [
    {
      employer: 'Freelancer',
      title: 'Freelance Embroidery Digitizer',
      dates: 'April 2021 – Present',
      bullets: [
        'Partnered with companies and international clients worldwide to deliver custom embroidery digitizing services on a freelance basis.',
        'Collaborated with international clients to deliver custom embroidery designs, utilizing advanced digitization techniques.',
        'Developed a reputation for precision and creativity in embroidery digitization through freelance work.',
        'Maintained a steady flow of freelance projects, ensuring timely delivery of high-quality embroidery designs.',
        'Employed effective time management skills to handle multiple freelance projects concurrently, maintaining high standards.',
        'Utilized freelance platforms to market digitizing services, expanding client base significantly.',
      ],
      sourceTrace:
        'Public display consolidated per business-owner decision 2026-09-18: employer names and per-employer responsibility bullets are no longer published (see revision note above). The freelance bullets are the CV 1 section\'s own Freelance entry (§2.4 row 12), plus a new "partnered with companies" point summarizing freelance work without naming specific companies.',
    },
  ] satisfies ExperienceEntry[],

  keySkills: [
    'Software Application',
    'Analyzing Data',
    'Audit Procedure',
    'Report preparation',
    'Quality Control',
    'Microsoft Excel, Word, PowerPoint',
    'Oracle ERP',
  ],

  education: {
    published: [
      { credential: 'Bachelor of Business Administration (BBA), Marketing', institution: 'Arid University of Rawalpindi', detail: 'CGPA 3.52' },
      { credential: 'FSc, Intermediate in Engineering', institution: 'Superior Group of Colleges, Lahore', detail: '60%' },
      { credential: 'Matriculation, Science', institution: 'Universal Public High School, Lahore', detail: '80%' },
      {
        credential: 'MBA, Marketing',
        institution: 'Leads University, Lahore',
        detail: 'Completed',
        sourceTrace:
          "Source text (CV 2 section only) reads 'Bachelor of Business Administrations(MBA Marketing Continue) • Leads University • Lahore • Last semester' — internally ambiguous between BBA-continuation and MBA. Published per business-owner decision using the source's own parenthetical degree name ('MBA Marketing') and presented as completed; the literal 'Continue'/'Last semester' source wording is not reused publicly. §2.4 row 13.",
      },
    ] satisfies EducationEntry[],
  },

  activities: ['Reading books', 'Taekwondo', 'Travel'],
} as const;
